services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: perfumes
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
  backend:
    build: ./Project5
    container_name: backend
    env_file:
      - ./Project5/.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./Front
    container_name: frontend
    env_file:
      - ./Front/.env
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
